name: Run Step Submitter

on:
  schedule:
    - cron: '30 21 * * *'   # UTC 21:30 = 北京次日 05:30
  workflow_dispatch:        # 手动按钮

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}
        run: python step.py
