name: Run Step Submitter
on:
  schedule:
    - cron: '30 21 * * *'
  workflow_dispatch:
jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - env:
          ACCOUNTS: ${{ secrets.ACCOUNTS }}
          SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}
        run: python step.py
